-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_COUNTRY foreign key (COUNTRY_ID) references CARDEALER_COUNTRY(ID)^
create index IDX_SEC_USER_ON_COUNTRY on SEC_USER (COUNTRY_ID)^
-- end SEC_USER
-- begin CARDEALER_CAR_MAKER
alter table CARDEALER_CAR_MAKER add constraint FK_CARDEALER_CAR_MAKER_ON_COUNTRY foreign key (COUNTRY_ID) references CARDEALER_COUNTRY(ID)^
create unique index IDX_CARDEALER_CAR_MAKER_UK_NAME on CARDEALER_CAR_MAKER (NAME) where DELETE_TS is null ^
create unique index IDX_CARDEALER_CAR_MAKER_UK_CODE on CARDEALER_CAR_MAKER (CODE) where DELETE_TS is null ^
create index IDX_CARDEALER_CAR_MAKER_ON_COUNTRY on CARDEALER_CAR_MAKER (COUNTRY_ID)^
-- end CARDEALER_CAR_MAKER
-- begin CARDEALER_CAR_MODEL
alter table CARDEALER_CAR_MODEL add constraint FK_CARDEALER_CAR_MODEL_ON_CAR_MAKER foreign key (CAR_MAKER_ID) references CARDEALER_CAR_MAKER(ID)^
create index IDX_CARDEALER_CAR_MODEL_ON_CAR_MAKER on CARDEALER_CAR_MODEL (CAR_MAKER_ID)^
-- end CARDEALER_CAR_MODEL
-- begin CARDEALER_EQUIPMENT
alter table CARDEALER_EQUIPMENT add constraint FK_CARDEALER_EQUIPMENT_ON_CAR_MODEL foreign key (CAR_MODEL_ID) references CARDEALER_CAR_MODEL(ID)^
create index IDX_CARDEALER_EQUIPMENT_ON_CAR_MODEL on CARDEALER_EQUIPMENT (CAR_MODEL_ID)^
-- end CARDEALER_EQUIPMENT
-- begin CARDEALER_COMPANY
alter table CARDEALER_COMPANY add constraint FK_CARDEALER_COMPANY_ON_ID foreign key (ID) references CARDEALER_CONTRACTOR(ID) on delete CASCADE^
-- end CARDEALER_COMPANY
-- begin CARDEALER_INDIVIDUAL
alter table CARDEALER_INDIVIDUAL add constraint FK_CARDEALER_INDIVIDUAL_ON_ID foreign key (ID) references CARDEALER_CONTRACTOR(ID) on delete CASCADE^
-- end CARDEALER_INDIVIDUAL
-- begin CARDEALER_CAR
alter table CARDEALER_CAR add constraint FK_CARDEALER_CAR_ON_CAR_MAKER foreign key (CAR_MAKER_ID) references CARDEALER_CAR_MAKER(ID)^
alter table CARDEALER_CAR add constraint FK_CARDEALER_CAR_ON_CAR_MODEL foreign key (CAR_MODEL_ID) references CARDEALER_CAR_MODEL(ID)^
alter table CARDEALER_CAR add constraint FK_CARDEALER_CAR_ON_EQUIPMENT foreign key (EQUIPMENT_ID) references CARDEALER_EQUIPMENT(ID)^
create index IDX_CARDEALER_CAR_ON_CAR_MAKER on CARDEALER_CAR (CAR_MAKER_ID)^
create index IDX_CARDEALER_CAR_ON_CAR_MODEL on CARDEALER_CAR (CAR_MODEL_ID)^
create index IDX_CARDEALER_CAR_ON_EQUIPMENT on CARDEALER_CAR (EQUIPMENT_ID)^
-- end CARDEALER_CAR
