alter table CARDEALER_EQUIPMENT add constraint FK_CARDEALER_EQUIPMENT_ON_CAR_MODEL foreign key (CAR_MODEL_ID) references CARDEALER_CAR_MODEL(ID);
create index IDX_CARDEALER_EQUIPMENT_ON_CAR_MODEL on CARDEALER_EQUIPMENT (CAR_MODEL_ID);
