alter table CARDEALER_ORDER add constraint FK_CARDEALER_ORDER_ON_CAR foreign key (CAR_ID) references CARDEALER_CAR(ID);
alter table CARDEALER_ORDER add constraint FK_CARDEALER_ORDER_ON_CONTRACTOR foreign key (CONTRACTOR_ID) references CARDEALER_CONTRACTOR(ID);
alter table CARDEALER_ORDER add constraint FK_CARDEALER_ORDER_ON_MANAGER foreign key (MANAGER_ID) references SEC_USER(ID);
create index IDX_CARDEALER_ORDER_ON_CAR on CARDEALER_ORDER (CAR_ID);
create index IDX_CARDEALER_ORDER_ON_CONTRACTOR on CARDEALER_ORDER (CONTRACTOR_ID);
create index IDX_CARDEALER_ORDER_ON_MANAGER on CARDEALER_ORDER (MANAGER_ID);
