alter table CARDEALER_CAR_MODEL add constraint FK_CARDEALER_CAR_MODEL_ON_CAR_MAKER foreign key (CAR_MAKER_ID) references CARDEALER_CAR_MAKER(ID);
create index IDX_CARDEALER_CAR_MODEL_ON_CAR_MAKER on CARDEALER_CAR_MODEL (CAR_MAKER_ID);
