alter table CARDEALER_CAR add constraint FK_CARDEALER_CAR_ON_CAR_MAKER foreign key (CAR_MAKER_ID) references CARDEALER_CAR_MAKER(ID);
alter table CARDEALER_CAR add constraint FK_CARDEALER_CAR_ON_CAR_MODEL foreign key (CAR_MODEL_ID) references CARDEALER_CAR_MODEL(ID);
alter table CARDEALER_CAR add constraint FK_CARDEALER_CAR_ON_EQUIPMENT foreign key (EQUIPMENT_ID) references CARDEALER_EQUIPMENT(ID);
create index IDX_CARDEALER_CAR_ON_CAR_MAKER on CARDEALER_CAR (CAR_MAKER_ID);
create index IDX_CARDEALER_CAR_ON_CAR_MODEL on CARDEALER_CAR (CAR_MODEL_ID);
create index IDX_CARDEALER_CAR_ON_EQUIPMENT on CARDEALER_CAR (EQUIPMENT_ID);
